version: '3'

services:
  db:
    container_name: chat_postgres
    image: postgres:latest
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    ports:
      - "5432:5432"
    networks:
      - fastapi_chat


  fastapi:
    container_name: chat_fastapi
    build:
      context: .
    command: >
      sh -c "
      alembic upgrade head &&
      uvicorn main:app --host 0.0.0.0 --reload"
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    networks:
      - fastapi_chat
    restart: always
    depends_on:
      db:
        condition: service_healthy


networks:
  fastapi_chat:
    driver: bridge